export enum ActionTypes {
  EXAMPLE = 'EXAMPLE',
  AIRLOCK_OPEN = 'AIRLOCK_OPEN',
  SCRY_STATE = 'SCRY_STATE',
  CONNECT_S3 = 'CONNECT_S3',

  CURRENT_SPACE_SET = 'CURRENT_SPACE_SET',
  CURRENT_TRAIL_SET = 'CURRENT_TRAIL_SET',

  S3_UPLOAD_DONE = 'S3_UPLOAD_DONE',

  GO_TO_PARENT = 'GO_TO_PARENT',

  LOADING_STATE_RESET   = 'LOADING_STATE_RESET',
  INITIAL_SET = 'INITIAL_SET',
  LOADING_SET = 'LOADING_SET',
  SUCCESS_SET = 'SUCCESS_SET',
  ERROR_SET   = 'ERROR_SET',
  DISABLED_SET   = 'DISABLED_SET',
}
