export enum GetterTypes {
  EXAMPLE_WITH_ARG = 'EXAMPLE_WITH_ARG',

  TREE_CONFIG = 'TREE_CONFIG',

  ELEMENT_INITIAL = 'ELEMENT_INITIAL',
  ELEMENT_LOADING = 'ELEMENT_LOADING',
  ELEMENT_SUCCESS = 'ELEMENT_SUCCESS',
  ELEMENT_ERROR = 'ELEMENT_ERROR',
  ELEMENT_STATUS_MAP = 'ELEMENT_STATUS_MAP',
}
